-- MySQL Script generated by MySQL Workbench
-- 07/28/14 12:31:30
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tps_mysql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tps_mysql` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tps_mysql` ;

-- -----------------------------------------------------
-- Table `tps_mysql`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tps_mysql`.`Status` (
  `statusID` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`statusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tps_mysql`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tps_mysql`.`Groups` (
  `groupID` INT NOT NULL AUTO_INCREMENT,
  `statusID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `startDate` VARCHAR(10) NOT NULL,
  `endDate` VARCHAR(10) NOT NULL,
  `customer` VARCHAR(45) NULL,
  `customerLocation` VARCHAR(45) NULL,
  PRIMARY KEY (`groupID`, `statusID`),
  UNIQUE INDEX `groupID_UNIQUE` (`groupID` ASC),
  INDEX `fk_Groups_Status1_idx` (`statusID` ASC),
  CONSTRAINT `fk_Groups_Status1`
    FOREIGN KEY (`statusID`)
    REFERENCES `tps_mysql`.`Status` (`statusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tps_mysql`.`Colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tps_mysql`.`Colors` (
  `colorID` INT NOT NULL AUTO_INCREMENT,
  `colorValue` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`colorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tps_mysql`.`Topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tps_mysql`.`Topics` (
  `topicID` INT NOT NULL AUTO_INCREMENT,
  `colorID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `technology` VARCHAR(45) NOT NULL,
  `technologyVersion` VARCHAR(45) NULL,
  `topicDescription` VARCHAR(45) NULL,
  PRIMARY KEY (`topicID`, `colorID`),
  UNIQUE INDEX `technologyID_UNIQUE` (`topicID` ASC),
  INDEX `fk_Topics_Colors1_idx` (`colorID` ASC),
  CONSTRAINT `fk_Topics_Colors1`
    FOREIGN KEY (`colorID`)
    REFERENCES `tps_mysql`.`Colors` (`colorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tps_mysql`.`Modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tps_mysql`.`Modules` (
  `moduleID` INT NOT NULL AUTO_INCREMENT,
  `groupID` INT NOT NULL,
  `topicID` INT NOT NULL,
  `startDate` VARCHAR(45) NOT NULL,
  `endDate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`moduleID`, `groupID`, `topicID`),
  INDEX `fk_Modules_Groups1_idx` (`groupID` ASC),
  INDEX `fk_Modules_Topics1_idx` (`topicID` ASC),
  CONSTRAINT `fk_Modules_Groups1`
    FOREIGN KEY (`groupID`)
    REFERENCES `tps_mysql`.`Groups` (`groupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modules_Topics1`
    FOREIGN KEY (`topicID`)
    REFERENCES `tps_mysql`.`Topics` (`topicID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tps_mysql`.`Trainers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tps_mysql`.`Trainers` (
  `trainerID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`trainerID`),
  UNIQUE INDEX `trainerID_UNIQUE` (`trainerID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tps_mysql`.`Supports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tps_mysql`.`Supports` (
  `supportID` INT NOT NULL AUTO_INCREMENT,
  `moduleID` INT NOT NULL,
  `groupID` INT NOT NULL,
  `topicID` INT NOT NULL,
  `trainerID` INT NOT NULL,
  PRIMARY KEY (`supportID`, `moduleID`, `groupID`, `topicID`, `trainerID`),
  UNIQUE INDEX `traineeID_UNIQUE` (`supportID` ASC),
  INDEX `fk_support_Modules1_idx` (`moduleID` ASC, `groupID` ASC, `topicID` ASC),
  INDEX `fk_Supports_Trainers1_idx` (`trainerID` ASC),
  CONSTRAINT `fk_support_Modules1`
    FOREIGN KEY (`moduleID` , `groupID` , `topicID`)
    REFERENCES `tps_mysql`.`Modules` (`moduleID` , `groupID` , `topicID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supports_Trainers1`
    FOREIGN KEY (`trainerID`)
    REFERENCES `tps_mysql`.`Trainers` (`trainerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tps_mysql`.`Availability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tps_mysql`.`Availability` (
  `availabilityID` INT NOT NULL,
  `trainerID` INT NOT NULL,
  `dayOff` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`availabilityID`, `trainerID`),
  INDEX `fk_Availability_Trainers1_idx` (`trainerID` ASC),
  CONSTRAINT `fk_Availability_Trainers1`
    FOREIGN KEY (`trainerID`)
    REFERENCES `tps_mysql`.`Trainers` (`trainerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tps_mysql`.`Trainees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tps_mysql`.`Trainees` (
  `traineeID` INT NOT NULL AUTO_INCREMENT,
  `groupID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`traineeID`, `groupID`),
  INDEX `fk_Trainees_Groups1_idx` (`groupID` ASC),
  CONSTRAINT `fk_Trainees_Groups1`
    FOREIGN KEY (`groupID`)
    REFERENCES `tps_mysql`.`Groups` (`groupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
